name: Replace Secrets

on: [ push, pull_request, workflow_dispatch ]

jobs:
  replace-secrets:
    name: Reemplazar Secretos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Secrets replacement
        uses: juanfdzz/secrets-replacer/actions/secrets-replacer-v1@main
        with:
          secrets: ${{ toJSON(secrets) }}
          files: values.yaml
          exclude_secret: ""